development:
  adapter: postgresql
  database: viajante_development
  encoding: unicode
  username: viajante
  password: Hbertorell0
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: viajante_test
  encoding: unicode
  username: viajante
  password: Hbertorell0
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d8bbreedlikars
  username: xjahbotbuviqih
  password: 8yc6RX65YACAtWliRdZcFV1dr7
  encoding: unicode
  port: 5432
  pool: 5
  timeout: 5000
